spring.application.name=agroflow-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/agroflow_db
spring.datasource.username=postgres
spring.datasource.password=AgroFlow@2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080